### ISSUE TITLE
bug求修复

### ISSUE THREAD

**Issue by jiangzhangpu** [roomanl/ArcgisTool#13]
再使用setMapClickCallBack方法里面写DefaultMapViewOnTouchListener方法时，如果结束当前地图界面再进来（不是软件退出再进来），所有的DefaultMapViewOnTouchListener里面的方法都不会触发了！求作者检测一下并修复

**Comment by roomanl** [comment]
已修复，修复后用法和原来有些不一样，具体内容请看更新日志和文档

**Comment by jiangzhangpu** [comment]
好的
