### ISSUE TITLE
请问这个报错怎么解决 Failed to resolve: com.github.roomanl:ArcgisTool:1.9

### ISSUE THREAD

**Issue by RisingAuroras** [roomanl/ArcgisTool#16]
我电脑开发项目，导入您的这个项目没有问题；但是放到其他人的电脑上却都报这个错误。。。
您能帮我出个注意吗

**Comment by roomanl** [comment]
添加maven { url 'https://jitpack.io' }
`allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}`

**Comment by RisingAuroras** [comment]
> 添加maven { url 'https://jitpack.io' } `allprojects { repositories { ... maven { url 'https://jitpack.io' } } }`

谢谢您的回复，但是我项目里有这个maven，我的项目在几个月前还可以导入，现在换电脑之后说一直找不到，目前我的解决方法是将aar和moudle 导入项目。
非常感谢您写的库，very nice！
