### ISSUE TITLE
哥，测绘好像不准确，面积大了好几倍

### ISSUE THREAD

**Issue by RisingAuroras** [roomanl/ArcgisTool#17]

**Comment by roomanl** [comment]
不会啊，旧版本是有偏大，是因为按平面去计算了，后面已经换成大地测量的API了

**Comment by RisingAuroras** [comment]
> 不会啊，旧版本是有偏大，是因为按平面去计算了，后面已经换成大地测量的API了

好的哥，我在找找我这边原因，会不会因为我用了天地图的图层，谢谢回复！
