### ISSUE TITLE
哥，如何android离线加载png瓦片图知道吗？按照z,x,y放的图片，没有配置文件

### ISSUE THREAD

**Issue by Lighthouse-Yang** [roomanl/ArcgisTool#18]
如何加载那？感谢感谢

**Comment by roomanl** [comment]
自定义一个类，继承ImageTiledLayer。然后重写byte[] getTile(TileKey tileKey)方法。TileKey可以获取x,y,z根据x,y,z去你SD卡里找到对应的瓦片。然后把瓦片转成byte[]返回。

**Comment by Lighthouse-Yang** [comment]
您好，我目前是这样试的，但是需要配置好多参数，我没法配置导致它寻找的瓦片不存在。如果您愿意的话能否帮我看看，我可以付出一点报酬感谢您。
他需要配置每一级的resolution、scale等等
@Override
    protected byte[] getTile(TileKey tileKey) {
        int level = tileKey.getLevel();
        int col = tileKey.getColumn();
        int row = tileKey.getRow();
        // 若缓存存在则返回缓存字节
        String fileName = row + ".png";

        File _cacheLevelDir = new File(CACHE_PATH + "/" + level + "/" +col);
        //本地存在
        File file = new File(_cacheLevelDir + "/" + fileName);
        Log.v("file", file.getPath());
        byte[] cachedBytes = null;
        cachedBytes = new byte[(int) file.length()];
        try {
            FileInputStream _fis = new FileInputStream(file);
            _fis.read(cachedBytes);
            _fis.close();
            return cachedBytes;
        } catch (IOException e) {
            e.printStackTrace();
        }

**Comment by roomanl** [comment]
我也没做过，你参考这个看看吧，https://blog.csdn.net/qq_16064871/article/details/80374729
