### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by Lighthouse-Yang** [roomanl/ArcgisTool#20]
博主您好，很感谢您开源的工具。使用我发现通过implementation 'com.github.roomanl:ArcgisTool:1.9'无法引入，只有通过implementation 'com.github.roomanl:ArcgisTool:+'可以引入，但是引入版本是1.8，并不是最新的版本。

**Comment by Lighthouse-Yang** [comment]
按照您提供的方法设置地图和工具监听，还是会冲突。

**Comment by Lighthouse-Yang** [comment]
这个是不是没有点击删除某一个标注的接口啊

**Comment by roomanl** [comment]
> 这个是不是没有点击删除某一个标注的接口啊

没有

**Comment by roomanl** [comment]
arcgis换了maven地址，导致1.9版本无法引入arcgis sdk。现在已经更换为最新的arcgis maven地址，请使用2.0

**Comment by Lighthouse-Yang** [comment]
那就只能通过查找当前点击的要素，然后删除呗
