### ISSUE TITLE
画图工具

### ISSUE THREAD

**Issue by giszh86** [roomanl/ArcgisTool#3]
把画图工具实现出来，这套工具就完美了
@roomanl

**Comment by roomanl** [comment]
画图不难，跟测量的绘制一样。现在没时间弄，有时间再加上绘制工具吧

**Comment by giszh86** [comment]
嗯，我现在还在用的10.x，过段时间再去升级100.x

**Comment by 786604724** [comment]
测量距离的好像也比实际的要偏大啊

**Comment by roomanl** [comment]
> 测量距离的好像也比实际的要偏大啊

距离测量都是直接使用arcgis自带有的测量API。如果测量数据不准确原因大概有2种，第一arcgis算的不准确。第二我把里面的单位换算的进率写错了。因为原来面积的换算也写错过。

**Comment by zhou199604** [comment]
> 测量距离的好像也比实际的要偏大啊

的确是arcgis接口偏大，用经纬度转平面计算好像可以了就

**Comment by roomanl** [comment]
> > 测量距离的好像也比实际的要偏大啊
> 
> 的确是arcgis接口偏大，用经纬度转平面计算好像可以了就

多谢提醒，你这么一说我才意识到代码里用的arcgis的API可能是平面测量。这里应该要用椭球测量才对。我仔细看了一下arcgis API。才发现有areaGeodetic和lengthGeodetic​两个测量API。这两个API就是椭球测量的。有空我改正一下

**Comment by roomanl** [comment]
测量偏大BUG已修复
